name: github_push

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  push-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.TOKEN_PUSH }}
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Dependency install
        run: npm install
      - name: Generate documentation
        run: npm run doc
      - name: Config repo
        run: |
          cd ./docs
          git config --local user.email "${{ secrets.USER_ACTION_EMAIL }}"
          git config --local user.name "${{ secrets.USER_ACTION_NAME }}"
          git init
      - name: Commit and push files
        run: |
          cd ./docs
          git config --local user.email "${{ secrets.USER_ACTION_EMAIL }}"
          git config --local user.name "${{ secrets.USER_ACTION_NAME }}"
          git add .
          git commit -m "test"
          git push -u https://${{ secrets.USER_NAME }}:${{ secrets.TOKEN_PUSH }}@github.com/${{ secrets.USER_NAME }}/${{ secrets.REPO_DOCS_NAME }}.git master -f